src/camera_panel/urls.py
from django.conf.urls import url

from camera_panel import views

urlpatterns = [
    url(r'saved-videos/$', views.VideosList.as_view(), name='saved_videos_list'),
    url(r'saved-video-preview/(?P<pk>[0-9]+)/$', views.SavedVideoPreview.as_view(), name='saved_video_preview'),
    url(r'online-video-preview/$', views.OnlineVideoPreview.as_view(), name='online_video_preview'),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('users.urls')),
    url(r'^camera/', include('camera_panel.urls', namespace='camera')),
    url(r'^settings/', include('settings_panel.urls', namespace='settings')),
    url(r'^api/', include('notifications.urls'))
]


# Add /media/ url to development server
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/users/urls.py
from django.conf.urls import url, include

from users import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='panel_index'),
    url(r'login/$', views.LoginView.as_view(), name='panel_login'),
    url(r'logout/$', views.LogoutView.as_view(), name='panel_logout'),
]

src/camera_panel/models.py
from django.conf import settings
from django.db import models
import subprocess

from settings_panel.tasks import send_command_to_camera


class Camera(models.Model):
    name = models.CharField(max_length=128, unique=True)
    port = models.IntegerField()
    address_ip = models.GenericIPAddressField(null=True)

    def listen_on_stream_socket(self):
        # TODO make in async to handle more than 1 camera
        subprocess.run(["python2", "core/scripts/python2/stream_video_fetcher_worker.py", self.name, str(self.port),
                        "{}/{}.jpg".format(settings.IMAGES_STREAM_FOLDER, self.name), settings.VIDEO_FOLDER])

    def update_object_using_client_camera_data(self):
        # this shouldn't be assync
        response = send_command_to_camera(self.address_ip, 'settings', send_type='get')
        data = response.json()
        for setting in data:
            setting_object = self.cameraintegersettings_set.filter(setting_variable_name=setting).first()
            if setting_object:
                setting_object.value = data[setting]
                setting_object.save()


class Video(models.Model):
    camera = models.ForeignKey(Camera)
    name = models.CharField(max_length=512)
    datetime_started = models.DateTimeField()

src/camera_panel/views.py
from django.views.generic import TemplateView, ListView
from django.views.generic.detail import DetailView

from camera_panel.models import Video


class VideosList(ListView):
    template_name = 'camera_panel/saved_videos_list.html'
    model = Video
    ordering = ["-datetime_started"]
    paginate_by = 50


class OnlineVideoPreview(TemplateView):
    template_name = 'camera_panel/online_video_preview.html'


class SavedVideoPreview(DetailView):
    template_name = 'camera_panel/saved_videos_preview.html'
    queryset = Video.objects.all()

src/camera_panel/templates/camera_panel/online_video_preview.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="row white-bg" style="padding: 15px;">
        {% include 'html_blocks/message_block.html'%}
        <div>
            <h1>Online camera preview</h1>
            <img src="/media/online-preview/camera1.jpg" id="camera_preview"/>

            <select class="form-control m-b" name="camera">
                <option>camera 1</option>
            </select>

        </div>
    </div>
{% endblock content %}

{% block javascript %}
    {{ block.super }}
    {# Update the image every 0.5 sec #}
    <script>
        function refresh_camera_image() {
                var myImageElement = document.getElementById('camera_preview');
                myImageElement.src = '/media/online-preview/camera1.jpg?rand=' + Math.random();
        }

        function reneveal_stream_ttl() {
                $.ajax({
                    url: '{{ SITE_URL|slice:"-1" }}{% url 'api_renew_camera_stream' %}',
                    type: 'POST',
                    contentType: 'application/json; charset=utf-8',
                    dataType: 'json', // same here
                    data: '{"camera_name": "camera1"}' {# TODO change it on variable when multiply cameras will be implemented #}
                }).done(console.log('done')).fail(console.log('fail'))
        }

        function online_preview_services() {
            refresh_camera_image();
            setInterval(refresh_camera_image, 500);

            reneveal_stream_ttl();
            setInterval(refresh_camera_image, 29000);
        }

        window.onload = online_preview_services;
    </script>
    <script>
        $(document).ready(function() {
            $('#menu-camera-ul').addClass('in');
            $('#menu-camera-online-preview').addClass('active');
            $('#menu-camera').addClass('active');
        });
    </script>
{% endblock %}

src/camera_panel/templates/camera_panel/saved_videos_list.html
{% extends 'base.html' %}


{% block content %}
    <div class="row white-bg" style="padding: 15px;">
        {% include 'html_blocks/message_block.html'%}
        <div>
            <h2>List of saved videos.</h2>

            {% if object_list %}
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Striped Table </h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>camera</th>
                                <th>name</th>
                                <th>recording time</th>
                                <th>preview</th>
                            </tr>
                            </thead>
                            <tbody>
                             {% for video in object_list %}
                                 <tr>
                                     <td>{{ forloop.counter }}</td>
                                     <td>{{ video.camera.name }}</td>
                                    <td>{{ video.name }}</td>
                                    <td>{{ video.datetime_started|date:"G:i d-m-Y" }}</td>
                                    <td><a class="btn btn-w-m btn-primary" href="{% url 'camera:saved_video_preview' pk=video.id %}">Preview video</a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>


            {% else %}
                 <h2>There is no saved videos!</h2>
            {% endif %}

             {% if is_paginated %}
                <div class="pagination text-center m">
                    <span class="page-links" style="font-size: 20px; margin-right: 50%">
                        {% if page_obj.has_previous %}
                            <a class="btn btn-w-m btn-primary" href="{% url 'camera:saved_videos_list' %}?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                        <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                        </span>
                        {% if page_obj.has_next %}
                            <a class="btn btn-w-m btn-primary" href="{% url 'camera:saved_videos_list' %}?page={{ page_obj.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
        </div>


    </div>
{% endblock content %}

{% block javascript %}
    {{ block.super }}
    <script>
        $(document).ready(function() {
            $('#menu-camera-ul').addClass('in');
            $('#menu-camera-saved-videos').addClass('active');
            $('#menu-camera').addClass('active');
        });

    </script>
{% endblock %}

src/camera_panel/templates/camera_panel/saved_videos_preview.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    {{ block.super }}
    <link href="{% static "css/videojs.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="row white-bg" style="padding: 15px;">
        {% include 'html_blocks/message_block.html'%}
        <div>
            <h1>Saved video preview.</h1>
            <p><b>Name</b>: {{ object.name }}</p>
            <p><b>Date</b>: {{ object.datetime_started|date:"G:i d-m-Y"  }}</p>
            <p><b>Camera</b>: {{ object.camera.name }}</p>

            <video id="video_player" class="video-js vjs-default-skin"
             controls autoplay preload="auto" width="600" height="480"
             data-setup='{"techorder" : ["flash"] }'>
                <source src="{{ VIDEOS_URL }}/{{ object.name }}" type='video/mp4' />
            </video>

        </div>
    </div>
    <a class='btn-w-m btn-primary' style="padding: 5px" href="{% url 'camera:saved_videos_list' %}">Back</a>
{% endblock content %}

{% block javascript %}
    {{ block.super }}
    <script src="{% static "js/video.js" %}"></script>
      <script>
        videojs.options.flash.swf = "video-js.swf";
      </script>
    <script>
        $(document).ready(function() {
            $('#menu-camera-saved-videos').addClass('active');
        });

    </script>
{% endblock %}